# Generated by Django 4.2.7 on 2023-11-11 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measurements',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.operator'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.report'),
        ),
    ]
